### PR TITLE
Fix update loop infinite loop

### LINKED ISSUE #169: infinite loop on panic during update
When an update fails outside of the update handler, a infinite loop occurs. Fix by failing the update instead of retrying in a loop.

### PR DESCRIPTION
**Pull request by MarinPostma**
fix update loop infinite loop in case of udpate error.

close #169

### CODE REVIEW

**Review by irevoire — DISMISSED** [review]
I had this bug yesterday!

**Comment by MarinPostma** [comment]
bors try

**Review by irevoire — APPROVED** [review]
lgtm

**Comment by irevoire** [comment]
bors merge

**Pull request merged**
