### PR TITLE
Rename update status "pending" into "enqueued"

### LINKED ISSUE #107: Update status value
The current update status in transplant is:
- `pending`
- `processing`
- `processed`
- `failed`

To stay iso, it should be:
- **`enqueued`**
- `processing`
- `processed`
- `failed`

⚠️ What's is breaking compared to the previous version of MeiliSearch: the `processing` status is now available which makes 4 states available instead of 3.

### PR DESCRIPTION
**Pull request by curquiza**
Closes #107

### CODE REVIEW

**Review by MarinPostma — APPROVED** [review]
thanks!

bors merge

**Comment by curquiza** [comment]
bors merge-

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
Bors does not like you @MarinPostma :jo

**Pull request merged**
