### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by MarinPostma**
This pr implements the error handling for meilisearch.

Rather than grouping errors by types, this implementation groups them by scope, each scope enclosing errors from a scope further down, or new errors within this scope. This makes the tracking of the origins of errors easier , and error handling easier at the module level.

All errors that are eventually returned to the user implement the `Into<ResponseError>` trait. `ReponseError` in turn implements the `ErrorCode` trait from `meilisearch-error`.

Some new errors have been introduced with the new engine for which we haven't defined error codes yet. It has been decided with @gmourier that those would return the `internal-error` code until the correct error code is specified.

### CODE REVIEW

**Review by irevoire — APPROVED** [review]
best PR I've seen so far :sunglasses:

**Review by curquiza — COMMENTED** [review]
Can you return a `content-type: application/json` when returning an error?

**Review by curquiza — COMMENTED** [review]
When pushing a badly formatted JSON document (for example the extra coma at the end of the line) I got a `bad_request` in v0.20.0 and now an `internal`. Can we change this?

**Review by curquiza — CHANGES_REQUESTED** [review]
Can we remove the `todo` from the update answer?

Capture d’écran 2021-06-21 à 14 44 06

**Comment by curquiza** [comment]
Related to my previous comment: missing primary key has already an error code -> https://docs.meilisearch.com/errors/#missing_primary_key

**Comment by MarinPostma** [comment]
@curquiza yeah sorry this part is unrelated to error codes, i just forgot to change the error type for updates :facepalm:

**Comment by curquiza** [comment]
Another feedback. Before there were two errors:
- [`missing_primary_key`](https://docs.meilisearch.com/errors/#missing_primary_key) -> there is no document in MeiliSearch, you try to insert document, but MeilISearch cannot find the primary key.
- [missing_document_id](https://docs.meilisearch.com/errors/#missing_document_id) -> there is already a defined primary key but the documents you try to push do not contain it.

Now, I only get the `missing_primay_key` error when doing my tests.

**Comment by curquiza** [comment]
When trying:
```
{
    "q": "",
    "filters": "genre = fantasy"
}
```

I get an internal error, but an error code already exists for this: [`bad_request`](https://docs.meilisearch.com/errors/#bad_request)

**Comment by MarinPostma** [comment]
> Another feedback. Before there were two errors:
>
> missing_primary_key -> there is no document in MeiliSearch, you try to insert document, but MeilISearch cannot find the primary key.
missing_document_id -> there is already a defined primary key but the documents you try to push do not contain it.
Now, I only get the missing_primay_key error when doing my tests.

I'm not the one returning this error, milli is, @ManyTheFish @Kerollmops, this one is one you guys ;)

**Comment by irevoire** [comment]
When I try to delete a non-existing index I get a totally different error between Meilisearch and Transplant:
image
(Meilisearch is on top)

**Comment by irevoire** [comment]
When I try to delete a non-existing index with:

http get localhost:$port/indexes/movies/documents/42

I get a totally different error between Meilisearch and Transplant:
image
 (Meilisearch is on top)

**Comment by curquiza** [comment]
Can we change the message to the v0.20 one?

Transplant
Capture d’écran 2021-06-22 à 12 18 47

MeiliSearch v0.20
Capture d’écran 2021-06-22 à 12 30 37

**Comment by curquiza** [comment]
Same for index not found:
Transplant
Capture d’écran 2021-06-22 à 12 33 34

Meilisearch v0.20
Capture d’écran 2021-06-22 à 12 32 52

**Comment by irevoire** [comment]
When looking for a non-existing update, don't get the same message as before:
Meilisearch: "Update 4 not found"
Transplant: "error with update: update 4 doesn't exist."

Feel free to close this comment if this is not an issue!

**Comment by irevoire** [comment]
When sending this request:
```
curl -v -X POST "localhost:$port/indexes/movies/search" --data '{ "q": "hello", "limit": 18446744073709551615 }
```
Meilisearch does not answer and transplant send:
```
{
  "message": "error with index: internal Index Error: panic",
  "errorCode": "internal",
  "errorType": "internal_error",
  "errorLink": "https://docs.meilisearch.com/errors#internal"
}
```

**Comment by irevoire** [comment]
When searching with the get route
``` 
curl -v -X GET "localhost:$port/indexes/movies/search?q=hello
```
I get this message:
```
{
  "message": "Query deserialize error: missing field `cropLength`",
  "errorCode": "bad_request",
  "errorType": "invalid_request_error",
  "errorLink": "https://docs.meilisearch.com/errors#bad_request"
}
```

I suspect this is unrelated to this issue; feel free to open another I issue from this comment if it's the case :slightly_smiling_face:

**Comment by curquiza** [comment]
Checked with @MarinPostma! Issues will be open for the message errors and will be fixed for the v0.21.0

**Review by curquiza — APPROVED** [review]

**Comment by MarinPostma** [comment]
bors merge

**Pull request merged**
