### PR TITLE
Fix dockerfile

### PR DESCRIPTION
**Pull request by curquiza**
docker build and run works now :)

### CODE REVIEW

**Comment by curquiza** [comment]
@shekhirin since it changed the dockerfile you updated, let us know if it impacts any of the work you did! 🙂
I checked (build + run), it should not change anything, but maybe I miss something.

**Comment by shekhirin** [comment]
@curquiza I didn't quite understand the change. We include workspace's root `Cargo.lock` into the image, but not the project's one from `meilisearch-http/Cargo.lock`. Why?

I think in order to get reproducible builds it's important to have dependencies locked. Maybe I miss something, though.

**Comment by curquiza** [comment]
We don't have any Cargo.lock in the workspaces now, so the build of the image currently fails on `main`.
Maybe @MarinPostma can explain better why we remove them.
In any case, when you build transplant (`cargo run`), it does not create any new cargo.lock in the workspaces, so for me, the cargo.lock at the root was enough.  But maybe I'm wrong.

**Comment by shekhirin** [comment]
oooh, I got it. Sorry, my fault. Agree with you, yeah!

**Review by MarinPostma — APPROVED** [review]
thanks @curquiza !

bors merge

**Pull request merged**
