### PR TITLE
Shared update store

### LINKED ISSUE #114: Update store redesign
The current design of the update store, with one update store per index is quite problematic:
- 1) It is complicated to make snapshot of, and require awkward locking mechanism
- 2) It sends updates in parrallel, but they are actually processed sequentially by the index actor, so multiple update nay be labelled as `processing`, while only one really is.

All the updates could be handled by a single update store to make things a lot easier to work with. It would also remove the need for a `write` channel in the `IndexActor` and simplify the code.

### PR DESCRIPTION
**Pull request by MarinPostma**
This PR changes the updates process so that only one instance of an update store is shared among indexes.

This allows updates to always be processed sequentially without additional synchronization, and fixes the bug where all the first pending update for each index were reported as processing whereas only one was.

EDIT:

I ended having to rewrite the whole `UpdateStore` to allow updates being really queued and processed sequentially in the ordered they were added. For that purpose I created a `pending_queue` that orders the updates by a global update id.

To find the next `update_id` to use, both globally and for each index, I have created another database that contains the next id to use.

Finally, all updates that have been processed (with success or otherwise) are all stores in an `updates` database.

The layout for the keys of these databases are such that it is easy to iterate over the elements for a particular index, and greatly reduces the amount of code to do so, compared to the former implementation.

I have also simplified the locking mechanism for the update store, thanks to the StateLock data structure, that allow both an arbitrary number of readers and a single writer to concurrently access the state. The current state can be either Idle, Processing, or Snapshotting. When an update or snapshotting is ongoing, the process holds the state lock until it is done processing its task. When it is done, it sets bask the state to Idle.

I have made other small improvements here and there, and have let some other for work, such as:
- When creating an update file to hold a request's content, it would be preferable to first create a temporary file, and then atomically persist it when we have written to it. This would simplify the case when there is no data to be written to the file, since we wouldn't have to take care about cleaning after ourselves.
- The logic for content validation must be factored.
- Some more tests related to error handling in the process_pending_update function.
- The issue #159

close #114

### CODE REVIEW

**Review by irevoire — DISMISSED** [review]

**Review by curquiza — DISMISSED** [review]
It works 😁
👏

**Review by curquiza — APPROVED** [review]

**Comment by MarinPostma** [comment]
bors merge

**Comment by MarinPostma** [comment]
bors try

**Review by irevoire — DISMISSED** [review]

**Review by irevoire — APPROVED** [review]

**Comment by irevoire** [comment]
bors try

**Comment by irevoire** [comment]
bors merge

**Pull request merged**
