### PR TITLE
Do not block when sending update notifications

### LINKED ISSUE #251: ReadTimeOut error
When trying to push the demo-rubygems dataset following the [README of the repo](https://github.com/meilisearch/demo-finding-rubygems), I get

```text
Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
```

But not in v0.20.0

### LINKED ISSUE #1430: ReadTimeOut error
When trying to push the demo-rubygems dataset following the [README of the repo](https://github.com/meilisearch/demo-finding-rubygems), I get

```text
Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
```

But not in v0.20.0

### PR DESCRIPTION
**Pull request by Kerollmops**
We tried this on a custom build with @curquiza and it works, it fixes #251, let me know what do you think about this fix.
It seems to be due to Transplant `panic`king from an `expect` which was closing the TCP connection on the Ruby side.

### CODE REVIEW

**Comment by irevoire** [comment]
Are you sure it's fixing the bug?
From what I read in the documentation now, you are just ignoring any error; if the channel is full, you tell the user you applied his update and give him an update number, while in reality, you might have just thrown away his update.
Also, you don't know if the update store encountered an error (for example, if you have no space left on your device, the update store must panic).

Personally, to me, all this code look super wrong, and I still don't think the previous code was panicking. If I put an explicit panic in the `register_update` function, this is what I get in the logs:
```
[2021-06-30T10:29:30Z INFO  actix_web::middleware::logger] 127.0.0.1:50764 "POST /indexes HTTP/1.1" 400 177 "-" "Ruby" 0.111465
thread 'tokio-runtime-worker' panicked at 'hello', meilisearch-http/src/index_controller/update_actor/store/mod.rs:248:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-06-30T10:29:30Z INFO  actix_web::middleware::logger] 127.0.0.1:50766 "POST /indexes/rubygems/settings HTTP/1.1" 500 146 "-" "Ruby" 0.005416
```
And this is what the ruby receive:
```
I, [2021-06-30T12:29:30.125123 #31243]  INFO -- : Index rubygems is ready.
/home/irevoire/demo-finding-rubygems/vendor/bundle/ruby/3.0.0/gems/meilisearch-0.13.0/lib/meilisearch/http_request.rb:75:in `validate': 500 Internal Server Error - Internal error: panic. See https://docs.meilisearch.com/errors#internal. (MeiliSearch::ApiError)
	from /home/irevoire/demo-finding-rubygems/vendor/bundle/ruby/3.0.0/gems/meilisearch-0.13.0/lib/meilisearch/http_request.rb:61:in `send_request'
	from /home/irevoire/demo-finding-rubygems/vendor/bundle/ruby/3.0.0/gems/meilisearch-0.13.0/lib/meilisearch/http_request.rb:28:in `http_post'
	from /home/irevoire/demo-finding-rubygems/vendor/bundle/ruby/3.0.0/gems/meilisearch-0.13.0/lib/meilisearch/index.rb:141:in `update_settings'
	from /home/irevoire/demo-finding-rubygems/meilisearch/feed_meilisearch.rb:12:in `feed_meilisearch_with'
	from /home/irevoire/demo-finding-rubygems/meilisearch/feed_meilisearch.rb:50:in `load_data_into_meilisearch'
	from meilisearch/app.rb:27:in `<main>'
```

BUT, for the ruby gem example, I get all my documents in the end, and I think it fixes the issue

**Comment by MarinPostma** [comment]
Yeah this is not a valid fix for me either, it hides the fact that the update loop is broken. This should be handled more graciously, but ignoring it is not a fix. And I don't understand how that is linked to the issue described by @curquiza. This may be hiding something else.

**Comment by irevoire** [comment]
I really don't understand why but it actually fixes the issue of @curquiza 
And the strangest thing to me is that, if change the:
```
       let _ = self.notification_sender.try_send(());
```
for a:
```
       self.notification_sender.try_send(()).unwrap();
```
I actually get a panic, which means this PR **SHOULD** be ignoring some update. But when I ignore all errors and look at the total number of documents, in the end, I have **all** my documents...

Personally, I think the issue is with the `while notification_receiver.recv().await.is_some()`, the content of this while takes more than **1 second** to execute! That is not normal!

**Comment by MarinPostma** [comment]
I think the send in the constructor should error out if it was closed. In the second case, the send should and is blocking. The issue is that the ruby sdk is flooding the channel with update request, so it has to wait until the sender is popped again and more space is available in the channel. Since it is only popped once all updated are processed, the client is left hanging for too long, hence the bug.

@Kerollmops your fix is not sufficient:
- we need to know when the channel was closed, so we need to handle the fact that the channel is full differently than when it was dropped
- we need a timeout mechanism so we are sure that no matter what the queue will be polled eventually after the client pushed an update (we had issues like that on meilisearch with the update store stalling)

**Comment by Kerollmops** [comment]
Ok, so I have made an update to this PR, it now panics when the channel has been closed on the other side which means that the update loop has been stopped (not good).

> we need a timeout mechanism so we are sure that no matter what the queue will be polled eventually after the client pushed an update (we had issues like that on meilisearch with the update store stalling).

I am not sure that this is a real issue, as [we put/commit before sending the update notification in the channel](https://github.com/meilisearch/transplant/blob/f1cc141f6c16efab9a238a9e365a7a7bc563605e/meilisearch-http/src/index_controller/update_actor/store/mod.rs#L243-L250), this means that if we can push, the update loop will be alerted about the new update. Otherwise, if the channel is full it means that it will eventually pull an update notification from the channel and process our newly added update.

**Comment by irevoire** [comment]
I just remembered that this channel was just a notification channel and nothing else; forget my previous message.

Now I actually understand why it works, and I like this fix :grin: 
I don't know why you changed the first check and removed the comment, though? When we create the update_store, it should not have any notification in it.
But whatever, it's not a big deal to me, and I approve this fix :+1:

**Review by irevoire — DISMISSED** [review]

**Comment by Kerollmops** [comment]
> I don't know why you changed the first check and removed the comment, though? When we create the update_store, it should not have any notification in it.

Yes, it should, it is important to run a first loop of the update store for when Transplant reboot, for example, it must process the updates that are already on the update store. This is why we send a notification in the channel, just to trigger a checks for pending updates.

**Comment by irevoire** [comment]
Yes I was just saying that at this point it was not a problem to use the `blocking_send` method since the `notification_sender` is supposed to be empty

**Review by curquiza — DISMISSED** [review]
It works with ruby SDK tests and the rubygems dataset import! 🎉 
Waiting for @MarinPostma

**Comment by curquiza** [comment]
Closed in favor of https://github.com/meilisearch/MeiliSearch/pull/1429

**Pull request closed without merging**
