### PR TITLE
fix(http, index): init analyzer with optional stop words

### PR DESCRIPTION
**Pull request by shekhirin**
Also bump `milli` and `meilisearch-tokenizer` packages versions

### CODE REVIEW

**Comment by shekhirin** [comment]
@curquiza hi there! I've bumped the tokenizer's version and supported new stop words init from https://github.com/meilisearch/Tokenizer/pull/31

**Comment by curquiza** [comment]
Hello @shekhirin! Thanks for your PR!! 😄 

I'm not sure we want to follow the `main` branch of Milli. I think it's safer to follow a commit SHA since Milli is not versionned. WDYT @MarinPostma?

**Review by MarinPostma — COMMENTED** [review]
I am putting this on hold until we have versioning on milli (this should not be long).

**Comment by curquiza** [comment]
Milli is now versioned -> https://github.com/meilisearch/milli :tada

**Comment by shekhirin** [comment]
@curquiza awesome, I've updated the dependencies so `milli` points to `v0.1.0` tag

**Review by MarinPostma — APPROVED** [review]
thanks a lot!

@curquiza this is a first step, afaik stop words will not be indexed, so they won't be highlighted, idk if that is the wanted behaviour.

bors merge

**Comment by curquiza** [comment]
@MarinPostma, thanks for explaining this behavior. Hopefully, this is the current behavior of the old MeiliSearch 😄 

Capture d’écran 2021-04-08 à 19 45 33

(v0.20.0 here)

Thank you so much @shekhirin for your PR! 🙏

**Pull request merged**
