### PR TITLE
Implements the dumps

### LINKED ISSUE #20: implement dumps
- https://docs.meilisearch.com/reference/api/dump.html#dumps
- https://docs.meilisearch.com/reference/features/dumps.html#dumps

### PR DESCRIPTION
**Pull request by irevoire**
closes #20

divergence from legacy meilisearch:
- dump v2 added, support loading of pending updates (only works dumps created from v2)
- added time stamps to the dump info
- Dump info are only persisted in an internal data structure, and they are not fetched from fs on demand anymore. This was a potential security flaw. This means that the dump infos are flushed on every restart.

### CODE REVIEW

**Review by curquiza — COMMENTED** [review]
Some remarks, I know it's not over so you might have already planned to update these points:
- the route to create a dump should return a 202, not a 200
- the `--dumps-dir` flag works when creating a dump (`POST` route), but impossible to retrieve a dump with the `GET` route, I got an error saying the dump does not exist
- The error message when a dump does not exist is `dump blabla does not exist not found`. I guess we will change this when implementing error handler but I wanted to notice it so that we do not forget it.

**Comment by curquiza** [comment]
Nope I would say I cannot get the status of my dumps using its ID when I use the --dumps-dir flag

**Comment by irevoire** [comment]
Finally we decided to re-implements the way meilisearch handle the dumps with the file system tricks. See this issue:
https://github.com/meilisearch/transplant/issues/190

**Comment by MarinPostma** [comment]
bors try

**Review by MarinPostma — DISMISSED** [review]

**Review by curquiza — CHANGES_REQUESTED** [review]
- An issue not present on `main`: I tried to reset all the settings (https://docs.meilisearch.com/reference/api/settings.html#reset-settings) and when I try to get the document I only get an array of empty objects.
- `--dump-batch-size` is usable in the CLI. It should not be accepted as a flag.

**Review by MarinPostma — APPROVED** [review]

**Comment by irevoire** [comment]
bors merge

**Pull request merged**
