### PR TITLE
return 202 on settings update / reset

### LINKED ISSUE #105: Settings update/reset should return a 202
The following routes should return a `202 Accepted`:
- `POST /indexes/:uid/settings`
- `DELETE /indexes/:uid/settings`

### PR DESCRIPTION
**Pull request by irevoire**
closes #105

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Can we also checked the `reset_settings` return a `202` in tests?

**Comment by irevoire** [comment]
let me know if this is enough

**Review by curquiza — APPROVED** [review]
LGTM 🐰 
but again let's wait for Marin's review 😇

**Review by MarinPostma — APPROVED** [review]
Thanks! 

bors merge

**Pull request merged**
