### PR TITLE
Update milli version to v0.5.0

### PR DESCRIPTION
**Pull request by curquiza**

### CODE REVIEW

**Comment by MarinPostma** [comment]
I'd like to merge #210 first if you don't mind :)

**Comment by irevoire** [comment]
aha, I was waiting for an update of milli before merging #188, but you renamed everything, I think thus, we can close #188 :slightly_smiling_face:

**Comment by curquiza** [comment]
I 've added the issue to the PR, thanks @irevoire :)

**Review by irevoire — DISMISSED** [review]

**Review by irevoire — APPROVED** [review]

**Review by MarinPostma — APPROVED** [review]
bors merge

**Pull request merged**
