### PR TITLE
Convert UpdateStatus to legacy meilisearch format

### LINKED ISSUE #78: Update status response
We need to come back to the previous behavior of the v0.19.0, about the display of the update status when calling the `indexes/:uid/updates` and `indexes/:uid/updates/:id` routes:

Here is the expected response template:

```jsx
[
    {
        "status": "processed",
        "updateId": 0,
        "type": {
            "name": "DocumentsAddition",
            "number": 6
        },
        "duration": 0.0160523,
        "enqueuedAt": "2021-03-02T19:45:46.919402700Z",
        "processedAt": "2021-03-02T19:45:46.937445Z"
    }
]
```

Replaces #47 and #48

Docs link -> https://docs.meilisearch.com/reference/api/updates.html#example

### PR DESCRIPTION
**Pull request by MarinPostma**
Returns the update statuses with the same format as legacy meilisearch.

The number of documents in a document addition/deletion is not known before processing, so it is only returned when the update is `processed`.

close #78 

associated milli PR: https://github.com/meilisearch/milli/pull/178

### CODE REVIEW

**Review by curquiza — DISMISSED** [review]
LGTMT (looks good to my tests)

**Comment by MarinPostma** [comment]
bors merge

**Comment by MarinPostma** [comment]
bors try

**Comment by MarinPostma** [comment]
bors try

**Review by irevoire — APPROVED** [review]

**Comment by MarinPostma** [comment]
bors merge

**Pull request merged**
