### PR TITLE
Implement all the CLI options

### LINKED ISSUE #206: Rename MAX_MDB_SIZE into MAX_INDEX_SIZE
Related to this spec: https://github.com/meilisearch/specifications/pull/48/files

- [x] Rename `--max-mdb-size` to `--max-index-size`
- [x] Rename `MAX_MDB_SIZE` to `MEILI_MAX_INDEX_SIZE`

Also, related to this issue: #204

### PR DESCRIPTION
**Pull request by irevoire**
closes #206 
And I looked into #204, I fixed some default values and tried to test as many options as possible, and I think the cli is already mostly working.
If someone knows any issues about it, I would like to hear more :slightly_smiling_face:

### CODE REVIEW

**Review by MarinPostma — APPROVED** [review]

**Comment by MarinPostma** [comment]
bors merge

**Review by curquiza — CHANGES_REQUESTED** [review]
The following options should not appear when using the `--help` flag:
- `--chunk-compression-level`
- `--chunk-compression-type`
- `--chunk-fusing-shrink-size`
- `--indexing-jobs`
- `--linked-hash-map-size`
- `--log-every-n`
- `--max-memory`
- `--max-nb-chunks`

**Comment by irevoire** [comment]
Good catch, I ensured every option in Meilisearch were present in transplant but forgot to check it the other way around :joy:

**Review by curquiza — APPROVED** [review]
🚀

**Comment by irevoire** [comment]
Since I ran rustfmt in my previous commit, I had many conflicts with #210, so I rewrote my previous commit to conflict with as few files as possible.
If you are ok with the PR, you can merge @MarinPostma :smile:

**Comment by MarinPostma** [comment]
lgtm codewise, @curquiza is this good with you?

**Review by curquiza — APPROVED** [review]
yes!

**Comment by MarinPostma** [comment]
bors merge

**Pull request merged**
